//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_client.PasswordHasher {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordHasher.IPasswordHasher")]
    public interface IPasswordHasher {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/GenerateSalt", ReplyAction="http://tempuri.org/IPasswordHasher/GenerateSaltResponse")]
        string GenerateSalt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/GenerateSalt", ReplyAction="http://tempuri.org/IPasswordHasher/GenerateSaltResponse")]
        System.Threading.Tasks.Task<string> GenerateSaltAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/HashPassword", ReplyAction="http://tempuri.org/IPasswordHasher/HashPasswordResponse")]
        string HashPassword(string password, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/HashPassword", ReplyAction="http://tempuri.org/IPasswordHasher/HashPasswordResponse")]
        System.Threading.Tasks.Task<string> HashPasswordAsync(string password, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/VerifyPassword", ReplyAction="http://tempuri.org/IPasswordHasher/VerifyPasswordResponse")]
        bool VerifyPassword(string inputPassword, string storedHash, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordHasher/VerifyPassword", ReplyAction="http://tempuri.org/IPasswordHasher/VerifyPasswordResponse")]
        System.Threading.Tasks.Task<bool> VerifyPasswordAsync(string inputPassword, string storedHash, string salt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPasswordHasherChannel : web_client.PasswordHasher.IPasswordHasher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordHasherClient : System.ServiceModel.ClientBase<web_client.PasswordHasher.IPasswordHasher>, web_client.PasswordHasher.IPasswordHasher {
        
        public PasswordHasherClient() {
        }
        
        public PasswordHasherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordHasherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordHasherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordHasherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateSalt() {
            return base.Channel.GenerateSalt();
        }
        
        public System.Threading.Tasks.Task<string> GenerateSaltAsync() {
            return base.Channel.GenerateSaltAsync();
        }
        
        public string HashPassword(string password, string salt) {
            return base.Channel.HashPassword(password, salt);
        }
        
        public System.Threading.Tasks.Task<string> HashPasswordAsync(string password, string salt) {
            return base.Channel.HashPasswordAsync(password, salt);
        }
        
        public bool VerifyPassword(string inputPassword, string storedHash, string salt) {
            return base.Channel.VerifyPassword(inputPassword, storedHash, salt);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyPasswordAsync(string inputPassword, string storedHash, string salt) {
            return base.Channel.VerifyPasswordAsync(inputPassword, storedHash, salt);
        }
    }
}
